export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS';
export const GET_CREDITS_SUCCESS = 'GET_CREDITS_SUCCESS';
